### ISSUE TITLE
geolocation not work

### ISSUE THREAD

**Issue by Romhast** [CheshireCaat/playwright-with-fingerprints#11]
I am using the following codes to change geolocation, but it gives an error and the page is closed. What is the correct usage?

```
const { plugin } = require('playwright-with-fingerprints');
const { readFile, writeFile } = require('fs/promises');

(async () => {
  // Get a fingerprint from the server:
  const fingerprint = await plugin.fetch('', {
    tags: ['Microsoft Windows', 'Chrome'],
  });
  await writeFile('fingerprint.json', fingerprint);
  plugin.useFingerprint(fingerprint);

  // Launch the browser instance:

  const browser = await plugin.launchPersistentContext("", {headless: false,
    permissions: ["geolocation", "microphone"],
    locale: 'de-DE',
    timezoneId: 'Europe/Berlin',
    geolocation: { longitude: 41.890221, latitude: 12.492348 }});


  // The rest of the code is the same as for a standard `playwright` library:
  const page = await browser.newPage();
  await page.goto('https://mylocation.org/');
})();
```

![image](https://github.com/CheshireCaat/playwright-with-fingerprints/assets/109461554/a9b887e2-eb8c-4844-8c83-ee10ecfa2357)

**Comment by CheshireCaat** [comment]
This website gives an error even when using regular **playwright**, so the problem here is either in the website itself or in the library, but not in the plugin:

![image](https://github.com/CheshireCaat/playwright-with-fingerprints/assets/30115373/af5d9f43-3f01-44ad-a59e-ccbc858e3155)

Example:

```js
const { chromium } = require('playwright');

(async () => {
  const context = await chromium.launchPersistentContext('', {
    headless: false,
    permissions: ['geolocation', 'microphone'],
    locale: 'de-DE',
    timezoneId: 'Europe/Berlin',
    geolocation: { longitude: 41.890221, latitude: 12.492348 },
  });

  const page = await context.newPage();
  await page.goto('https://mylocation.org/');
})();
```

Try increasing the page load timeout and changing the **waituntil** property in the **goto** method options. For the future, check for an issue without using the plugin before reporting it.

**Comment by Romhast** [comment]
> This website gives an error even when using regular **playwright**, so the problem here is either in the website itself or in the library, but not in the plugin:
> 
> ![image](https://user-images.githubusercontent.com/30115373/255354344-af5d9f43-3f01-44ad-a59e-ccbc858e3155.png)
> 
> Example:
> 
> ```js
> const { chromium } = require('playwright');
> 
> (async () => {
>   const context = await chromium.launchPersistentContext('', {
>     headless: false,
>     permissions: ['geolocation', 'microphone'],
>     locale: 'de-DE',
>     timezoneId: 'Europe/Berlin',
>     geolocation: { longitude: 41.890221, latitude: 12.492348 },
>   });
> 
>   const page = await context.newPage();
>   await page.goto('https://mylocation.org/');
> })();
> ```
> 
> Try increasing the page load timeout and changing the **waituntil** property in the **goto** method options. For the future, check for an issue without using the plugin before reporting it.

I used the codes you posted and it works fine for me. but playwright-with-fingerprints gives page not loading error

**this normal playwright**
![image](https://github.com/CheshireCaat/playwright-with-fingerprints/assets/109461554/4828447c-d1ed-4432-8035-d07e02f5612b)

**This too playwright-with-fingerprints**
![image](https://github.com/CheshireCaat/playwright-with-fingerprints/assets/109461554/93ce9b59-8b5d-4dd2-8e77-496078c399a9)

**Comment by CheshireCaat** [comment]
Okay, I'll reopen the ticket, but at the moment I can't help - I don't have a similar problem on two different machines.

**Comment by Romhast** [comment]
> Okay, I'll reopen the ticket, but at the moment I can't help - I don't have a similar problem on two different machines.

thank you, not only for this site, if i change geolocation values, i can't do any search, it gives me page failed to load error every time.

**Comment by bablosoft** [comment]
I can't reproduce issue either. Try to localize issue, by finding which exact option causes crash

**Comment by Romhast** [comment]
> I can't reproduce issue either. Try to localize issue, by finding which exact option causes crash

Using permission and geolocation at the same time causes a crash

**Comment by bablosoft** [comment]
Can you update minimal example

**Comment by Romhast** [comment]
> Can you update minimal example

this code can be used without any crash but location information can never be allowed, it is changed to block every time

```
const { plugin } = require('playwright-with-fingerprints');
const { readFile, writeFile } = require('fs/promises');

(async () => {
  // Get a fingerprint from the server:
  const fingerprint = await plugin.fetch('', {
    tags: ['Microsoft Windows', 'Chrome'],
  });
  await writeFile('fingerprint.json', fingerprint);
  plugin.useFingerprint(fingerprint);

  // Launch the browser instance:

  const browser = await plugin.launchPersistentContext("", {
    headless: false,
    permissions: ["microphone"],
    locale: 'de-DE',
    timezoneId: 'Europe/Berlin',
    geolocation: { longitude: 41.890221, latitude: 12.492348 }});


  // The rest of the code is the same as for a standard `playwright` library:
  const page = await browser.newPage();
  await page.goto('https://mylocation.org/');
})();
```
this code will crash because permission geolocation is used and it will crash 5-10 seconds after page load


```
const { plugin } = require('playwright-with-fingerprints');
const { readFile, writeFile } = require('fs/promises');

(async () => {
  // Get a fingerprint from the server:
  const fingerprint = await plugin.fetch('', {
    tags: ['Microsoft Windows', 'Chrome'],
  });
  await writeFile('fingerprint.json', fingerprint);
  plugin.useFingerprint(fingerprint);

  // Launch the browser instance:

  const browser = await plugin.launchPersistentContext("", {
    headless: false,
    permissions: ["geolocation", "microphone"],
    locale: 'de-DE',
    timezoneId: 'Europe/Berlin',
    geolocation: { longitude: 41.890221, latitude: 12.492348 }});


  // The rest of the code is the same as for a standard `playwright` library:
  const page = await browser.newPage();
  await page.goto('https://mylocation.org/');
})();
```

**Comment by bablosoft** [comment]
@CheshireCaat, we probably need to block `permissions` config key if it causes problems. What do you think?

-----------------

@Romhast, in any case this example is sort of theoretical.

```javascript
plugin.useProxy('127.0.0.1:8080', {
  // Change browser timezone according to proxy:
  changeTimezone: true,
  // Replace browser geolocation according to proxy:
  changeGeolocation: true,
});
```

Following code should be used to set geolocation and other browser settings related to language.

**Comment by Romhast** [comment]
> @CheshireCaat, we probably need to block `permissions` config key if it causes problems. What do you think?
> 
> @Romhast, in any case this example is sort of theoretical.
> 
> ```js
> plugin.useProxy('127.0.0.1:8080', {
>   // Change browser timezone according to proxy:
>   changeTimezone: true,
>   // Replace browser geolocation according to proxy:
>   changeGeolocation: true,
> });
> ```
> 
> Following code should be used to set geolocation and other browser settings related to language.

if i use this code it won't crash but i can't change the location in any way. for example this code has no function.

`  await browser.setGeolocation({ latitude: 59.95, longitude: 30.31667 });`

**Comment by bablosoft** [comment]
@Romhast, yes, because geolocation is set according to proxy automatically

**Comment by Romhast** [comment]
> @Romhast, yes, because geolocation is set according to proxy automatically

I used fingerprint puppeteer, she has the same problem, for your information, I can take a video if you want.

**Comment by bablosoft** [comment]
Please create ticket with minimal number of actions in corresponding repository.

Also note, that priority will be far from high.

That is because the browser shouldn't crash, but it also shouldn't work as you expect to. Geolocation will be overridden with proxy settings anyway.

**Comment by Romhast** [comment]
> Please create ticket with minimal number of actions in corresponding repository.
> 
> Also note, that priority will be far from high.
> 
> That is because the browser shouldn't crash, but it also shouldn't work as you expect to. Geolocation will be overridden with proxy settings anyway.

I wonder if this error exists only for the free version, could it be working properly in the premium version?

**Comment by MacMarde** [comment]
> [@CheshireCaat](https://github.com/CheshireCaat), we probably need to block `permissions` config key if it causes problems. What do you think?
> 
> [@Romhast](https://github.com/Romhast), in any case this example is sort of theoretical.
> 
> plugin.useProxy('127.0.0.1:8080', {
>   // Change browser timezone according to proxy:
>   changeTimezone: true,
>   // Replace browser geolocation according to proxy:
>   changeGeolocation: true,
> });
> 
> Following code should be used to set geolocation and other browser settings related to language.

This is also not working for me. 
I get the following error in the Debug Console:

`[ERROR] DESKTOP [MAIN-ERROR] Error running desktop bot: PluginError: Failed to get proxy ip`
