### ISSUE TITLE
google rcaptcha problem

### ISSUE THREAD

**Issue by Romhast** [CheshireCaat/playwright-with-fingerprints#13]
Although I use fingerprint switcher, google sends recaptcha after a certain time, is there a way to bypass this or how does it detect it?

![image](https://github.com/CheshireCaat/playwright-with-fingerprints/assets/109461554/dd22e15a-eea7-445a-94af-fbe5ab87cc70)

**Comment by bablosoft** [comment]
This is probably because you are not using proxies.

If it is not the case please write to email, like this:

https://community.bablosoft.com/topic/12199
