### ISSUE TITLE
Service 

### ISSUE THREAD

**Issue by ATISI7** [CheshireCaat/playwright-with-fingerprints#18]
I need to download as many fingerprints as possible from your database for a thesis project, using the free version I should be able to download one every 3 minutes, however, after downloading one for the first time I always get the following message (despite the 3 minutes having passed):

"{\"valid\":false,\"message\":\"Key is empty\"}"

The code used is the following:

import { plugin } from 'playwright-with-fingerprints';
import * as fs from 'node:fs/promises'; 

plugin.version = 'default';
let i = 0;
const fp = [];

(async () => {
    while( i < 3){
        // Get a fingerprint from the server:
        const fingerprint = await plugin.fetch("",{});     
        fp.push(fingerprint);
            
        await fs.appendFile('downloadedFingerprintPROVA.json',JSON.stringify(fp[i]));

        i++;

        await waitThreeMinutes();
    }
})();

function waitThreeMinutes() {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve();
      }, 3 * 60 * 1000); // 3 minuti in millisecondi (1 minuto = 60 secondi, 1 secondo = 1000 millisecondi)
    });
  }

**Comment by bablosoft** [comment]
please use following tags with free version `['Microsoft Windows', 'Chrome']`

**Comment by ATISI7** [comment]
Thank you, can i use only this two tags in the free version?

**Comment by bablosoft** [comment]
yes
