### ISSUE TITLE
Package not supported on M1 Macbook

### ISSUE THREAD

**Issue by Ben2701** [CheshireCaat/playwright-with-fingerprints#25]
I just wanted to install the package using "npm i playwright-with-fingerprints"

But i got this error:
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for browser-with-fingerprints@1.5.4: wanted {"os":"win32","arch":"ia32,x64"} (current: {"os":"darwin","arch":"arm64"})
npm ERR! notsup Valid OS:    win32
npm ERR! notsup Valid Arch:  ia32,x64
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: arm64

**Comment by bablosoft** [comment]
Only windows is supported
