### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by trentod** [CheshireCaat/playwright-with-fingerprints#3]
I have a premium key for fingerprinting, how can i enable multithreading?

**Comment by CheshireCaat** [comment]
What do you mean?

Currently, there is only one limitation - parallel calls to several functions to launch a browser or get a fingerprint are synchronized between threads. This is necessary to avoid race conditions when the plugin works with the browser and engine.

After that, you work with the browser in the same way as in a regular framework - there are no restrictions.

**Comment by trentod** [comment]
I'm just trying to run 10 instances at the same time like i used to do with playwright or BAS multithreaded.
Anyway, thanks for explanation.

**Comment by bablosoft** [comment]
@trentod, reason for reopen?
