### ISSUE TITLE
Uncaught Error: Unsupported OS architecture for named mutex.

### ISSUE THREAD

**Issue by A-UNSAL** [CheshireCaat/playwright-with-fingerprints#34]
The error I got when I wanted to use it with [nwjs](https://nwjs.io/)
I am using Windows 10 and 64 bit operating system.
node -v / v21.7.1
![image](https://github.com/CheshireCaat/playwright-with-fingerprints/assets/6368139/50bd54ec-76d0-4ce3-a9b9-d03633779bc9)

**Comment by CheshireCaat** [comment]
You cannot use this plugin in the context of a browser, I am not familiar with **nwjs**, but apparently it performs part of the logic in the browser, which is unacceptable.

You need to make sure that the code is executed on the **node** side, for example, in **electron**, **IPC** is used for this, try to do or find an analogue.

**Comment by A-UNSAL** [comment]
I get the same error in node mode.
