### ISSUE TITLE
Setting the FINGERPRINT_CWD environment variable has no effect.

### ISSUE THREAD

**Issue by sergerdn** [CheshireCaat/playwright-with-fingerprints#4]
I know that this project uses https://github.com/CheshireCaat/browser-with-fingerprints/ to download its dependencies. 

Based on the source code at https://github.com/CheshireCaat/browser-with-fingerprints/blob/ecbfe450b64c6ae2e822cef3ba31791068f760a5/src/plugin/connector/index.js#L6, it should use an environment variable. However, it seems that the environment variable is not being used, and the default `data` directory is being created when the script is run instead of `FINGERPRINT_CWD.`

I believe it happened because that line of code executed before I set the environment variable in some cases.

Did I miss something?

`.env`:
```
FINGERPRINT_CWD="./.dd"

```
```javascript 
import dotenv from 'dotenv'

dotenv.config()


import * as path from "path"
import * as fs from "fs"
import * as os from "os"

import {plugin} from 'playwright-with-fingerprints'

async function runRemote(profileDirectory) {
  const fingerprint = await plugin.fetch('', {
    tags: ['Microsoft Windows', 'Chrome'],
  });

  plugin.useFingerprint(fingerprint)

  const browser = await plugin.launchPersistentContext(profileDirectory, {
    headless: false,
    args: ['--start-maximized']
  })


  console.log("Browser launched")
}

(async () => {
  console.log(process.env["FINGERPRINT_CWD"]) // printed .dd

  const profileDirectory = fs.mkdtempSync(path.join(os.tmpdir(), "chrome-profile-"));
  await runRemote(profileDirectory)
})();

```

**Comment by CheshireCaat** [comment]
It seems to be more related to imports or something wrong with `dotenv`. Please check it:

https://github.com/motdotla/dotenv#how-do-i-use-dotenv-with-import
https://github.com/motdotla/dotenv/issues/133#issuecomment-255298822

You can also use this kind of import, for me it seems even more convenient:

```js
import 'dotenv/config';
```

In this case, such problems will not arise.
