### ISSUE TITLE
A question about cdp session

### ISSUE THREAD

**Issue by Mbaspfd** [CheshireCaat/playwright-with-fingerprints#40]
Will I be able to hide the open cdp session with this module? Or should I use patched Chromium to hide the cdp session? I ask because many antibot systems can easily detect automation in Chrome

**Comment by CheshireCaat** [comment]
The engine used in plugins and in **BAS** bypasses **CDP** checks without problems.

If you have examples where this is not the case, you can specify them so that we can check and refine them.
