### ISSUE TITLE
Work directory size keeps growing

### ISSUE THREAD

**Issue by victornor** [CheshireCaat/playwright-with-fingerprints#43]
I have 8 work directories, after around 10-20 reuses of each directory the total size has grown to over 50gb.
Is there any way to clear whatever is being stored there without having to re-download or re-install the browser?

**Comment by CheshireCaat** [comment]
The size of the working folder may grow due to the creation of temporary profiles, they are not cleared automatically. They are located in the working folder, inside the **profiles** directory.

You can clean it before starting or after finishing the work.

**Comment by victornor** [comment]
Okay great. I will clear them on my end. Would be a nice feature to have them auto clear though.
