### ISSUE TITLE
BAS Chromium 128 is detected on pixelscan.net

### ISSUE THREAD

**Issue by dr3adx** [CheshireCaat/playwright-with-fingerprints#49]
Latest engine chromium 128 is detected on pixelscan.net as automation framework

**Comment by bablosoft** [comment]
No, it is not. Please avoid open tickets before testing it.

**Comment by dr3adx** [comment]
Man I'm literally swapping engine versions from 127 and 128 without
changing anything and it's detected, even tested clean install
Use this playwright plugin to test not your BAS

**Comment by bablosoft** [comment]
As I said previously, avoid open tickets before testing it.

**Comment by dr3adx** [comment]
But ofcourse I tested it many times, previous versions are not detected,
only latest engine 128 "browser.17", I had to roll back to 127

**Comment by bablosoft** [comment]
<img width="1124" alt="BrowserAutomationStudio_2024-10-02_00-12-32" src="https://github.com/user-attachments/assets/ffe9eb38-6188-4c72-a642-777fc227a773">

**Comment by dr3adx** [comment]
> <img alt="BrowserAutomationStudio_2024-10-02_00-12-32" width="1124" src="https://private-user-images.githubusercontent.com/19365536/372653033-ffe9eb38-6188-4c72-a642-777fc227a773.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NDk4NTIsIm5iZiI6MTcyNzg0OTU1MiwicGF0aCI6Ii8xOTM2NTUzNi8zNzI2NTMwMzMtZmZlOWViMzgtNjE4OC00YzcyLWE2NDItNzc3ZmMyMjdhNzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA2MTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NWU2NzRiNTgyOTU5ZDFjNWM0MDZjZTYwMzU3ZTUzMmQ0YmUzZTQxNWU5ZDRjYTk5ZTZiNDk1YzQ0MTI5ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aq608i5JLlGlgGrkSPMkJxLF2SteZ5FfdjMi6uPdwxM">

but i told you already to NOT use your BAS application and use playwright-with-fingerprints, because the Chrome starting flags are different

**Comment by dr3adx** [comment]
@bablosoft please test it again with **playwright-with-fingerprints** not bas
