### ISSUE TITLE
Linux is not supported although promised

### ISSUE THREAD

**Issue by VasilyVP** [CheshireCaat/playwright-with-fingerprints#50]
If try to install on Linux such error message happens: 
`Unsupported platform for bas-remote-node@1.5.4: wanted {"os":"win32"} (current: {"os":"linux"})`

**Comment by CheshireCaat** [comment]
Promised where? The documentation and other texts clearly state that there is no unix version of the system and it is not planned in the near future.

You may be confused with the description of the fingerprint service - you can use it to emulate a browser from other operating systems, but this is a completely different question.

**Comment by VasilyVP** [comment]
> Promised where? The documentation and other texts clearly state that there is no unix version of the package and it is not planned in the near future.
> 
> You may be confused with the description of the fingerprint service - you can use it to emulate a browser from other operating systems, but this is a completely different question.

yes, it was confusing. But it's really not clear and this info hidden deep. Sorry for disturb
