### ISSUE TITLE
[Bug]: Engine.dll is detected as a malicious program

### ISSUE THREAD

**Issue by alexandre-vl** [CheshireCaat/playwright-with-fingerprints#55]
Engine.dll is detected as a malicious program by windows defender so the script cannot run.

**Streps to reproduce**
1. Just launch a blank browser with the plugin and wait for browser installation.

**Expected behavior**
Do you think it would be possible to prevent it from being detected as a virus of one kind or another?
Do I need to sign the code with a code-signing certificate? If so, can I sign the code and create a zip for myself?

**Screenshots**
<img width="419" alt="Screenshot 2024-10-11 at 13 47 17" src="https://github.com/user-attachments/assets/0587dc10-3816-46b3-94a7-baf89af7a0c7">
![image1](https://github.com/user-attachments/assets/3570d9db-6c15-4d64-8c00-20ebfbadddcf)

**System :**
 - Plugin version ^2.0.2
 - Engine version 27.9.2
 - Node version v18.19.1

**Comment by bablosoft** [comment]
False positive.

**Comment by alexandre-vl** [comment]
Hey @bablosoft, what about my questions ? 
> Do you think it would be possible to prevent it from being detected as a virus of one kind or another?
> Do I need to sign the code with a code-signing certificate? If so, can I sign the code and create a zip for myself?

**Comment by bablosoft** [comment]
Code signing cert will be added eventually, but mostly it is AV problem.
