### ISSUE TITLE
[Bug]: Failed to get proxy ip happens often

### ISSUE THREAD

**Issue by VasilyVP** [CheshireCaat/playwright-with-fingerprints#57]
On a regular basis appears exception with a message "Failed to get proxy ip"
I use ipInfoMethod: 'ip-api.com',
Regardless of using ipExtractionURL parameter.

Each proxy is checked right before using.

**Expected behavior**
Such exception expected to be very rare.

**System (please complete the following information):**
 - Plugin version 2.0.4
 - Node version 20.17.0

**Additional context**
Each proxy is used once (in one plugin session) and is not reused for a long time.

**Comment by CheshireCaat** [comment]
Greetings!

The `ipInfoMethod` parameter is responsible for obtaining detailed data about the IP address, while `ipExtractionURL` refers specifically to the settings for obtaining the address itself.

If you do not change the `ipExtractionURL` parameter, then the default IP detection method is used, with which you probably have problems.

Therefore, you need to choose the service that suits you and specify the necessary settings, [here](https://github.com/CheshireCaat/browser-with-fingerprints/blob/0368b3805a50c584c4d94c5a23fd4f7b664f207d/test/proxy.js#L6) are the examples with which I am testing the basic plugin.

**Comment by VasilyVP** [comment]
Set up this configuration from the test:
{
        ipExtractionURL: 'https://api.ipify.org/',
        ipExtractionMethod: 'raw',
        ipExtractionParam: '',
},
The issue is still exists

**Comment by CheshireCaat** [comment]
Can you send an example of a problematic proxy to the mail - likangt2012@gmail.com?

**Comment by VasilyVP** [comment]
I can't to send specific proxy, but I'm pretty sure there is no issue there. It happens often but randomly with different proxies regardless which ipExtractionURL was used. First time appeared yesterday. Also I got several times strange `Failed to get page https://api.ipify.org/ with HttpClient` - it's playwright response.

Can I set detectExternalIP: false if ipInfoMethod: 'ip-api.com', returns the ip with other info?

**Comment by CheshireCaat** [comment]
> Can I set detectExternalIP: false since ipInfoMethod: 'ip-api.com' returns the ip as well?

No, as I stated above, these settings are responsible for different things. If you disable IP detection, then the proxy parameter substitution may be incomplete. If this is OK for you then you can disable it.

> Also I got several times strange

Can you show the minimum code that causes the problem? This is an error from the engine, not from playwright. It's very strange, but I have no other assumptions now, except that the proxies themselves at a random moment in time cannot access websites to determine the IP - maybe you have a proxy with rotation and the IP determination occurs at the moment of change?

**Comment by CheshireCaat** [comment]
As far as I know the `ip-api` service doesn't provide output IP address as a result, it returns only geolocation data. Therefore, it seems to me that it is not necessary and should not be combined.

> Mb it make sense to repeat request in case of fail

You can do it on your side, something like this:

```js
const fingerprint = await plugin.fetch({
  tags: ['Microsoft Windows', 'Chrome'],
});

plugin.useFingerprint(fingerprint);
plugin.useProxy(proxyUrl, {
  ipExtractionURL: 'https://api.ipify.org/',
  ipExtractionMethod: 'raw',
  ipExtractionParam: '',
  ipInfoMethod: 'ip-api.com',
  changeGeolocation: true,
});

try {
  const context = await plugin.launch({
    headless: false,
    ignoreHTTPSErrors: true,
  });
} catch {
  // check error message and repeat if necessary
}

```

It may also be useful to enable the `changeGeolocation` option in conjunction with the `ipInfoMethod`, otherwise the location replacement will be incomplete.

**Comment by VasilyVP** [comment]
> As far as I know the `ip-api` service doesn't provide output IP address as a result, it returns only geolocation data. Therefore, it seems to me that it is not necessary and should not be combined.
> 

`curl -x "<proxy>" http://ip-api.com`
return something like:
```
{
  "status"       : "success",
  "continent"    : "North America",
  "continentCode": "NA",
  "country"      : "United States",
  "countryCode"  : "US",
  "region"       : "MI",
  "regionName"   : "Michigan",
  "city"         : "Birch Run",
  "district"     : "",
  "zip"          : "48415",
  "lat"          : 43.2674,
  "lon"          : -83.7877,
  "timezone"     : "America/Detroit",
  "offset"       : -18000,
  "currency"     : "USD",
  "isp"          : "Charter Communications",
  "org"          : "Spectrum",
  "as"           : "AS20115 Charter Communications",
  "asname"       : "CHARTER-20115",
  "mobile"       : false,
  "proxy"        : false,
  "hosting"      : false,
  "query"        : "47.224.39.167"
}
```
`query` - is IP

> > Mb it make sense to repeat request in case of fail
> 
> You can do it on your side, something like this:
> 
> ```js
> const fingerprint = await plugin.fetch({
>   tags: ['Microsoft Windows', 'Chrome'],
> });
> 
> plugin.useFingerprint(fingerprint);
> plugin.useProxy(proxyUrl, {
>   ipExtractionURL: 'https://api.ipify.org/',
>   ipExtractionMethod: 'raw',
>   ipExtractionParam: '',
>   ipInfoMethod: 'ip-api.com',
>   changeGeolocation: true,
> });
> 
> try {
>   const context = await plugin.launch({
>     headless: false,
>     ignoreHTTPSErrors: true,
>   });
> } catch {
>   // check error message and repeat if necessary
> }
> ```
Yeah, will do this way
> 
> It may also be useful to enable the `changeGeolocation` option in conjunction with the `ipInfoMethod`, otherwise the location replacement will be incomplete.
