### ISSUE TITLE
[Bug]: Failed to connect to Browser using CDP WebSocket URL

### ISSUE THREAD

**Issue by sergerdn** [CheshireCaat/playwright-with-fingerprints#58]
The script hangs when attempting to connect to the browser using `chromium.connect()` with a timeout set to `0` (no timeout). 

When a timeout value is specified (e.g., 10000ms), the following error occurs:  `browserType.connect: Timeout 10000ms exceeded.`  

**Steps to reproduce** and **code example**:

I created a simple script as provided in the documentation: https://github.com/CheshireCaat/playwright-with-fingerprints?tab=readme-ov-file#launching-the-browser

 ```javascript
const { plugin } = require('playwright-with-fingerprints');
const { chromium } = require('playwright');
const path = require('path');

(async () => {
  // Define the base directory and working folder for storing data
  const baseDir = path.normalize(path.join(path.dirname(require.main.filename), '..'));
  const workingFolder = path.normalize(path.join(baseDir, '.data'));
  plugin.setWorkingFolder(workingFolder);

  // Launch a browser instance with the plugin
  const chrome = await plugin.spawn({ headless: false });
  const wsEndpoint = chrome.url;
  console.log('chrome launched, wsEndpoint: ', wsEndpoint);

  // BUG: The script hangs before this point if the timeout is set to 0 (no timeout).
  // If a timeout is set, the following error is encountered:
  // Error message: browserType.connect: Timeout 10000ms exceeded.
  const browser = await chromium.connect(wsEndpoint, {
    timeout: 10000,
  });
  console.log('browser');

  const page = await browser.newPage();
  await page.goto('https://google.com/?hl=en');
  console.log('page');

  await browser.close();
  await chrome.close();
})();
```
**Expected behavior**

The script should successfully connect to the browser instance using the WebSocket URL provided by `plugin.spawn()` without timing out.

**System:**

- Plugin version:
```json
"dependencies": {
    "playwright": "1.49.1",
    "playwright-with-fingerprints": "2.0.5"
  },
```
- Node version: `v22.11.0`

**Comment by sergerdn** [comment]
I want to point out that my main working path involves starting the browser from this plugin and then connecting to the WebSocket endpoint URL from another script. 

This is why this functionality is so important to me.

**Comment by CheshireCaat** [comment]
@sergerdn it seems to me that it's `playwright` related issue. I'll try to figure it out, but not as a priority. You can use an alternative method to connect:

```js
const chrome = await plugin.spawn({ headless: false });
const wsEndpoint = chrome.url;
console.log('chrome launched, wsEndpoint: ', wsEndpoint);

const browser = await chromium.connectOverCDP(`http://localhost:${chrome.port}`, {
  timeout: 10000,
});
console.log('browser');
```

**Comment by sergerdn** [comment]
> You can use an alternative method to connect:

Thanks, it works! 

However, for some reason, after I connect via `chromium.connectOverCDP`, it opens a new browser window. 
Is that normal? I was expecting a new browser tab, not a new window.

<img width="1368" alt="1" src="https://github.com/user-attachments/assets/a7bff217-3ad5-4c95-a388-fa1d60fafdf5" />

**Comment by CheshireCaat** [comment]
Yes, this is how it works, because your code creates separate context (window), if you wanna reuse window, you can work directly with default browser context, i.e:

```js
const defaultContext = browser.contexts()[0];

const page = await defaultContext.newPage();
await page.goto('https://google.com/?hl=en');
console.log('page');

await browser.close();
await chrome.close();
```

**Comment by sergerdn** [comment]
@CheshireCaat 

Thank you so much, you saved me a lot of time!

**Comment by dr3adx** [comment]
> Yes, this is how it works, because your code creates separate context (window), if you wanna reuse window, you can work directly with default browser context, i.e:
> 
> const defaultContext = browser.contexts()[0];
> 
> const page = await defaultContext.newPage();
> await page.goto('https://google.com/?hl=en');
> console.log('page');
> 
> await browser.close();
> await chrome.close();

hello, any idea why chatgpt.com shows unsolvable captcha only after connectOverCDP is used?
if browser is just .spawned without connectOverCDP chatgpt.com shows no captcha and can be used fine
seems like they detect the CDP connection. Got any idea how to evade it?
